/**
 * haar.ts — where the faces are, using a real face detector.
 *
 * The page has no server, no library and no runtime, so until now the face search
 * was built out of the picture itself: skin has a fairly narrow range of colour, so
 * a mask of skin-coloured pixels plus a tidy-up found *something*. Measured on
 * eighteen ordinary photographs on 19 September 2026 it found a box on twelve of
 * them and missed eight of the fifteen faces an independent detector named — and on
 * the practise photographs it drew a box covering 77% of the picture, because a
 * warm-toned portrait is mostly skin-coloured. A rule about colour is not a rule
 * about faces.
 *
 * So the search is now Viola-Jones: the algorithm behind OpenCV's frontal-face
 * cascade, written here in plain loops over typed arrays. The numbers it reads
 * are OpenCV's own (`src/cascade-data.ts`, generated by `tools/build-cascade.mjs`),
 * and that is the one piece of this project that is not written from scratch — a
 * trained cascade is data, and it carries its own licence, reproduced in the
 * generated file. The detector's arithmetic was checked against OpenCV 4.10 on the
 * same pictures: every box OpenCV draws, this draws.
 *
 * HOW IT WORKS, in one paragraph. A window 24 pixels square walks the picture at
 * every position and every size. At each stop it looks at a few hundred
 * black-and-white "which side is darker" questions — is the eye band darker than the
 * cheeks, is the bridge of the nose lighter than its sides — and asks them in order
 * of how decisive they are. Each question is asked only if every cheaper question
 * before it passed, so almost every window is thrown out after two or three looks.
 * A window that answers all twenty-five rounds is a face. The questions and their
 * thresholds are the cascade; the asking is this file.
 *
 * It is still a PROPOSER, not an authority, and it is worth saying what it will
 * still miss, because the page has to stay usable when the guess is wrong: a face
 * turned away from the camera, a face in heavy shadow, a face behind a mask or a
 * hand, and a face smaller than about a twelfth of the picture. Every box it draws
 * can be removed by hand and a missing one drawn by hand, which is why a proposer
 * is allowed to be wrong.
 */

import {
  FEATURE_RECT_COUNT,
  FEATURE_RECT_FIRST,
  RECT_WEIGHT,
  RECT_XYWH,
  STAGE_STUMP_COUNT,
  STAGE_STUMP_FIRST,
  STAGE_THRESHOLD,
  STUMP_FEATURE,
  STUMP_LEFT,
  STUMP_RIGHT,
  STUMP_THRESHOLD,
} from './cascade-data.js';
import type { Box, Frame } from './faces.js';

/** The window the cascade was trained for. Everything else is measured from it. */
const WINDOW = 24;

/** How much the window grows each pass. OpenCV's default, and the same one here. */
const SCALE_STEP = 1.1;

/** The normalisation rectangle: the window with a one-pixel border removed. */
const NORM_X = 1;
const NORM_Y = 1;
const NORM_W = WINDOW - 2;
const NORM_H = WINDOW - 2;

/**
 * How flat a window may be before it is not worth asking about.
 *
 * OpenCV skips a window whose standard deviation is not above 10 in the picture it
 * searched. This search scales the *window* rather than the picture, so the same
 * rule reads as "sigma above 10 times the scale".
 */
const LEAST_SIGMA = 10;

/** Two boxes on one face are one face; two people are not. */
const SAME_FACE = 0.3;

/** Nobody needs more boxes than this, and it bounds the work. */
const MOST_FACES = 6;

/** Everything the cascade needs, decoded once, on first use. */
interface Cascade {
  featureRectFirst: Int32Array;
  featureRectCount: Int32Array;
  rectXYWH: Uint8Array;
  rectWeight: Float32Array;
  stageThreshold: Float32Array;
  stageStumpFirst: Int32Array;
  stageStumpCount: Int32Array;
  stumpFeature: Int32Array;
  stumpThreshold: Float32Array;
  stumpLeft: Float32Array;
  stumpRight: Float32Array;
}

/**
 * Base64 back to bytes.
 *
 * The arrays are stored as base64 of their own buffer, not as a list of numbers,
 * so the file stays a sixth of the size and — the part that matters — a `Float32`
 * threshold is the *same* number OpenCV holds rather than a decimal reading of it.
 */
function bytesOf(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function float32(base64: string): Float32Array {
  return new Float32Array(bytesOf(base64).buffer);
}

function int32(base64: string): Int32Array {
  return new Int32Array(bytesOf(base64).buffer);
}

let decoded: Cascade | null = null;

function cascade(): Cascade {
  if (!decoded) {
    decoded = {
      featureRectFirst: int32(FEATURE_RECT_FIRST),
      featureRectCount: int32(FEATURE_RECT_COUNT),
      rectXYWH: bytesOf(RECT_XYWH),
      rectWeight: float32(RECT_WEIGHT),
      stageThreshold: float32(STAGE_THRESHOLD),
      stageStumpFirst: int32(STAGE_STUMP_FIRST),
      stageStumpCount: int32(STAGE_STUMP_COUNT),
      stumpFeature: int32(STUMP_FEATURE),
      stumpThreshold: float32(STUMP_THRESHOLD),
      stumpLeft: float32(STUMP_LEFT),
      stumpRight: float32(STUMP_RIGHT),
    };
  }
  return decoded;
}

/** One window size, with its rectangle coordinates worked out in advance. */
interface Scale {
  /** The window's side in picture pixels. */
  window: number;
  /** How far the window moves between stops. Two until the window is 48 across. */
  step: number;
  /** The window's rectangles, four numbers each: x, y, width, height. */
  rects: Int32Array;
  /** The normalisation rectangle, which is what the window's contrast is measured over. */
  normLeft: number;
  normTop: number;
  normWidth: number;
  normHeight: number;
  normArea: number;
}

/**
 * Every rectangle for one window size.
 *
 * Worked out once per size rather than once per stop: a stop would otherwise pay
 * four multiplications and four roundings for each of the cascade's 6,383
 * rectangles, at every one of a hundred thousand stops.
 */
function scaleFor(window: number, c: Cascade): Scale {
  const share = window / WINDOW;
  const count = c.rectXYWH.length / 4;
  const rects = new Int32Array(count * 4);
  for (let i = 0; i < count; i += 1) {
    const from = i * 4;
    rects[from] = Math.round(c.rectXYWH[from] * share);
    rects[from + 1] = Math.round(c.rectXYWH[from + 1] * share);
    rects[from + 2] = Math.round(c.rectXYWH[from + 2] * share);
    rects[from + 3] = Math.round(c.rectXYWH[from + 3] * share);
  }
  const normWidth = Math.round(NORM_W * share);
  const normHeight = Math.round(NORM_H * share);
  return {
    window,
    step: share >= 2 ? 1 : 2,
    rects,
    normLeft: Math.round(NORM_X * share),
    normTop: Math.round(NORM_Y * share),
    normWidth,
    normHeight,
    normArea: normWidth * normHeight,
  };
}

/** Luminance, 0-255, the way OpenCV's grey conversion weighs it. */
function greyOf(rgb: Uint8Array, pixels: number): Uint8Array {
  const grey = new Uint8Array(pixels);
  for (let i = 0, p = 0; i < pixels; i += 1, p += 3) {
    grey[i] = (rgb[p] * 0.299 + rgb[p + 1] * 0.587 + rgb[p + 2] * 0.114 + 0.5) | 0;
  }
  return grey;
}

/**
 * The summed-area table: `out[y, x]` is the total of everything above and left of
 * `y, x`. It turns "what is the total of this rectangle" from a walk over the
 * rectangle into four lookups, which is the whole reason this algorithm runs at all
 * — the window asks the same rectangles over and over.
 *
 * Held as doubles rather than 32-bit integers on purpose. The table of *squares*
 * reaches 65,025 per pixel, which overflows a signed 32-bit integer at about 33,000
 * pixels — smaller than one face-sized window in a large photograph — and an
 * overflow here does not fail loudly, it makes a face look flat.
 */
function summedArea(grey: Uint8Array, width: number, height: number, squares: boolean): Float64Array {
  const stride = width + 1;
  const out = new Float64Array(stride * (height + 1));
  for (let y = 0; y < height; y += 1) {
    let rowTotal = 0;
    const row = y * width;
    const above = y * stride;
    const here = (y + 1) * stride;
    for (let x = 0; x < width; x += 1) {
      const value = grey[row + x];
      rowTotal += squares ? value * value : value;
      out[here + x + 1] = out[above + x + 1] + rowTotal;
    }
  }
  return out;
}

/** How much two boxes cover each other, as a share of the smaller one. */
function overlap(a: Box, b: Box): number {
  const left = Math.max(a.x, b.x);
  const top = Math.max(a.y, b.y);
  const right = Math.min(a.x + a.w, b.x + b.w);
  const bottom = Math.min(a.y + a.h, b.y + b.h);
  if (right <= left || bottom <= top) return 0;
  return ((right - left) * (bottom - top)) / Math.min(a.w * a.h, b.w * b.h);
}

/**
 * Every window that survived, boiled down to one box per face.
 *
 * A cascade answers "yes, a face" at several neighbouring stops and several sizes
 * around one head — that is not several faces, it is the same face found repeatedly.
 * The boxes are grouped by overlap and each group is averaged, which is roughly what
 * OpenCV's own grouping does and lands closer to the true size of the face than
 * keeping the largest would: the largest passing window is usually slightly bigger
 * than the head.
 */
function oneBoxPerFace(hits: Box[]): Box[] {
  const groups: Box[][] = [];
  for (const hit of [...hits].sort((a, b) => b.w * b.h - a.w * a.h)) {
    const group = groups.find((g) => g.some((other) => overlap(other, hit) > SAME_FACE));
    if (group) group.push(hit);
    else groups.push([hit]);
  }
  return groups.map((group) => {
    let x = 0;
    let y = 0;
    let w = 0;
    let h = 0;
    for (const box of group) {
      x += box.x;
      y += box.y;
      w += box.w;
      h += box.h;
    }
    const n = group.length;
    return { x: Math.round(x / n), y: Math.round(y / n), w: Math.round(w / n), h: Math.round(h / n) };
  });
}

/**
 * The faces in a picture, left to right.
 *
 * Empty when there are none — which is a real answer, not a failure, and the page
 * treats it as "name the whole picture instead".
 *
 * TWO THINGS THAT LOOKED LIKE OBVIOUS SAVINGS AND COST A FACE, so that nobody spends
 * the afternoon finding them again. Both were measured against the same thirty-eight
 * photographs, and both are in this one function's shape:
 *
 *   - **Stopping the pyramid at a window covering 60% of the picture** — sensible on
 *     its face, since a head that fills the frame is a crop, and it saves the most
 *     expensive sizes. It also lost the face in one of the twenty practise
 *     photographs outright. The pyramid runs to the picture's own size.
 *   - **Stepping two pixels everywhere instead of one above double the window** —
 *     a quarter of the stops, and about two and a half times faster, and it lost
 *     three faces. `scaleFor` keeps OpenCV's rule.
 *
 * What is left costs roughly a quarter of a second per picture, and that is the price
 * of finding the faces at all. It is paid once, while a picture is being opened.
 */
export function detectFaces(frame: Frame): Box[] {
  const { rgb, width, height } = frame;
  if (width < WINDOW || height < WINDOW) return [];

  const c = cascade();
  const grey = greyOf(rgb, width * height);
  const area = summedArea(grey, width, height, false);
  const squares = summedArea(grey, width, height, true);
  const stride = width + 1;

  const most = Math.min(width, height);
  const hits: Box[] = [];

  for (let factor = 1; ; factor *= SCALE_STEP) {
    const window = Math.round(WINDOW * factor);
    if (window > most) break;
    const s = scaleFor(window, c);
    const { rects, step } = s;

    const lastX = width - window;
    const lastY = height - window;

    for (let y = 0; y <= lastY; y += step) {
      const normRow = (y + s.normTop) * stride;

      for (let x = 0; x <= lastX; x += step) {
        // How much the window's contrast varies. A flat window — a wall, a sky —
        // cannot be a face and is not worth 25 rounds of questions.
        const normRight = x + s.normLeft + s.normWidth;
        const normBottom = (y + s.normTop + s.normHeight) * stride;
        const left = x + s.normLeft;
        const total =
          area[normBottom + normRight] - area[normRow + normRight] - area[normBottom + left] + area[normRow + left];
        const squareTotal =
          squares[normBottom + normRight] -
          squares[normRow + normRight] -
          squares[normBottom + left] +
          squares[normRow + left];
        const spread = s.normArea * squareTotal - total * total;
        if (spread <= 0) continue;
        // `sqrt(spread)` is the window's area times its standard deviation, so this
        // is that deviation in grey levels. OpenCV refuses a window flatter than 10,
        // measured in the picture it searched — which is this picture divided by the
        // factor, so a bigger window is allowed to be flatter by the same amount.
        const deviation = Math.sqrt(spread) / s.normArea;
        if (deviation <= LEAST_SIGMA * factor) continue;
        const norm = 1 / Math.sqrt(spread);

        let passed = true;
        for (let stage = 0; stage < c.stageThreshold.length; stage += 1) {
          const first = c.stageStumpFirst[stage];
          const count = c.stageStumpCount[stage];
          let score = 0;

          for (let k = 0; k < count; k += 1) {
            const stump = first + k;
            const feature = c.stumpFeature[stump];
            const from = c.featureRectFirst[feature];
            const rectsOf = c.featureRectCount[feature];
            let value = 0;

            for (let r = 0; r < rectsOf; r += 1) {
              const at = (from + r) * 4;
              const rx = x + rects[at];
              const ry = y + rects[at + 1];
              const right = rx + rects[at + 2];
              const bottomEdge = ry + rects[at + 3];
              const top = ry * stride;
              const low = bottomEdge * stride;
              // Rectangle: black on one side, white on the other. The weights are
              // set so a uniform patch scores zero.
              value +=
                c.rectWeight[from + r] *
                (area[low + right] - area[top + right] - area[low + rx] + area[top + rx]);
            }

            score += value * norm < c.stumpThreshold[stump] ? c.stumpLeft[stump] : c.stumpRight[stump];
          }

          if (score < c.stageThreshold[stage]) {
            passed = false;
            break;
          }
        }

        if (passed) hits.push({ x, y, w: window, h: window });
      }
    }
  }

  const backX = frame.sourceWidth / width;
  const backY = frame.sourceHeight / height;
  return oneBoxPerFace(hits)
    .sort((a, b) => a.x - b.x)
    .slice(0, MOST_FACES)
    .map((box) => ({
      x: Math.round(box.x * backX),
      y: Math.round(box.y * backY),
      w: Math.round(box.w * backX),
      h: Math.round(box.h * backY),
    }));
}
